nav:
  - About:
    - about.md
    - Installation: installation-guide.md
  - README/
  - Library:
    - index.md
    - Everything.md
    - EverythingSafe.md
    - '*'

preserve_directory_names: true

sort:
  sections: mixed